<?php

$galaxyspecial = "Seed income is 50% OFF!";
$statustext = "(placeholder)";

$urgentmessage = "";

$contactemail = '(email)';

$daisy_latestversionint = 600;
$daisy_latestversionstring = '6.00';

//$flowers = array('Rose','Daisy','Iris','Orchid','Sunflower','Tulip');
$flowers = array('Rose','Daisy','Iris','Orchid','Sunflower');
$flowers_plural = array('Roses','Daisies','Irises','Orchids','Sunflowers');
$flowers_id = array('Rose' => 0,'Daisy' => 1,'Iris' => 2,'Orchid' => 3,'Sunflower' => 4);

$autowater_cost = 100;
$fertilizer_cost = 200;
$superfertilizer_cost = 20;

$debug = false;

$funfacts = array(
	"The warp music was made by Evershine.",
	"The original server was written in Java.",
	"Origami Rose existed for J2ME.",
	"There was a flower called Origami Buttercup that was only avalible on iOS.",
	"This server was written in PHP."
);

$countries = array(
	"ad@Andorra",
	"ae@United Arab Emirates",
	"af@Afghanistan",
	"ag@Antigua and Barbuda",
	"ai@Anguilla",
	"al@Albania",
	"am@Armenia",
	"an@Netherlands Antilles",
	"ao@Angola",
	"ar@Argentina",
	"as@American Samoa",
	"at@Austria",
	"au@Austrailia",
	"aw@Aruba",
	"ax@Aland",
	"az@Azerbaijan",
	"ba@Bosnia and Herzegovina",
	"bb@Barbados",
	"bd@Bangladesh",
	"be@Belgium",
	"bf@Burkina Faso",
	"bg@Bulgaria",
	"bh@Bahrain",
	"bi@Burundi",
	"bj@Benin",
	"bm@Bermuda",
	"bn@Brunei Darussalam",
	"bo@Bolivia",
	"br@Brazil",
	"bs@Bahamas",
	"bt@Bhutan",
	"bw@Botswana",
	"by@Belarus",
	"bz@Belize",
	"ca@Canada",
	"cc@Cocos Islands",
	"cd@Congo, Democratic Republic of the",
	"cf@Central African Republic",
	"cg@Congo",
	"ch@Switzerland",
	"ci@Cote d'Ivoire",
	"ck@Cook Islands",
	"cl@Chile",
	"cm@Cameroon",
	"cn@China",
	"co@Colombia",
	"cr@Costa Rica",
	"cu@Cuba",
	"cv@Cape Verde",
	"cx@Christmas Island",
	"cy@Cyprus",
	"cz@Czech Republic",
	"de@Germany",
	"dj@Djibouti",
	"dk@Denmark",
	"dm@Dominica",
	"do@Dominican Republic",
	"dz@Algeria",
	"ec@Ecuador",
	"ee@Estonia",
	"eg@Egypt",
	"eh@Western Sahara",
	"en@England",
	"er@Eritrea",
	"es@Spain",
	"et@Ethiopia",
	"fam@Famfamfam Flag",
	"fi@Finland",
	"fj@Fiji",
	"fk@Falkland Islands",
	"fm@Micronesia",
	"fo@Faroe Islands",
	"fr@France",
	"ga@Gabon",
	"gb@United Kingdom",
	"gd@Grenada",
	"ge@Georgia",
	"gh@Ghana",
	"gi@Gibraltar",
	"gl@Greenland",
	"gm@Gambia",
	"gn@Guinea",
	"gp@Guadeloupe",
	"gq@Equatorial Guinea",
	"gr@Greece",
	"gs@South Georgia and the South Sandwich Islands",
	"gt@Guatemala",
	"gu@Guam",
	"gw@Guinea-Bissau",
	"gy@Guyana",
	"hk@Hong Kong",
	"hn@Honduras",
	"hr@Croatia",
	"ht@Haiti",
	"hu@Hungary",
	"id@Indonesia",
	"ie@Irland",
	"il@Israel",
	"in@India",
	"io@British Indian Ocean Territory",
	"iq@Iraq",
	"ir@Iran",
	"is@Iceland",
	"it@Italy",
	"jm@Jamaica",
	"jo@Jordan",
	"jp@Japan",
	"ke@Kenya",
	"kg@Kyrgyzstan",
	"kh@Cambodia",
	"ki@Kiribati",
	"km@Comoros",
	"kn@Saint Kitts and Nevis",
	"kp@North Korea",
	"kr@South Korea",
	"kw@Kuwait",
	"ky@Cayman Islands",
	"kz@Kazakhstan",
	"la@Laos",
	"lb@Lebanon",
	"lc@Saint Lucia",
	"li@Liechtenstein",
	"lk@Sri Lanka",
	"lr@Liberia",
	"ls@Lesotho",
	"lt@Lithuania",
	"lu@Luxembourg",
	"lv@Latvia",
	"ly@Libyan Arab Jamahiriya",
	"ma@Morocco",
	"mc@Monaco",
	"md@Moldova",
	"me@Montenegro",
	"mg@Madagascar",
	"mh@Marshall Island",
	"mk@Macedonia",
	"ml@Mali",
	"mm@Myanmar",
	"mn@Mongolia",
	"mo@Macao",
	"mp@Northern Mariana Islands",
	"mq@Martinique",
	"mr@Mauritania",
	"ms@Montserrat",
	"mt@Malta",
	"mu@Mauritius",
	"mv@Maldives",
	"mw@Malawi",
	"mx@Mexico",
	"my@Malaysia",
	"mz@Mozambique",
	"na@Nambia",
	"nc@New Caledonia",
	"ne@Niger",
	"nf@Norfolk Island",
	"ng@Nigeria",
	"ni@Nicaragua",
	"nl@Netherlands",
	"no@Norway",
	"np@Nepal",
	"nr@Nauru",
	"nu@Niue",
	"nz@New Zealand",
	"om@Oman",
	"pa@Panama",
	"pe@Peru",
	"pf@French Polynesia",
	"pg@Papua New Guinea",
	"ph@Philippines",
	"pk@Pakistan",
	"pl@Poland",
	"pm@Saint Pierre and Miquelon",
	"pn@Pitcairn",
	"pr@Puerto Rico",
	"ps@Palestinian Territory",
	"pt@Portugal",
	"pw@Palau",
	"py@Paraguay",
	"qa@Qatar",
	"ro@Romania",
	"rs@Serbia",
	"ru@Russia",
	"rw@Rwanda",
	"sa@Saudi Arabia",
	"sb@Solomon Islands",
	"sc@Seychelles",
	"scotland@Scotland",
	"sd@Sudan",
	"se@Sweden",
	"sg@Singapore",
	"sh@Saint Helena",
	"si@Slovenia",
	"sk@Slovakia",
	"sl@Sierra Leone",
	"sm@San Marino",
	"sn@Senegal",
	"so@Somalia",
	"sr@Suriname",
	"st@Sao Tome and Principe",
	"sv@El Salvador",
	"sy@Syrian Arab Republic",
	"sz@Swaziland",
	"tc@Turks and Caicos Islands",
	"td@Chad",
	"tf@French Southern Territories",
	"tg@Togo",
	"th@Thailand",
	"tj@Tajikistan",
	"tk@Tokelau",
	"tl@Timor-Leste",
	"tm@Turkmenistan",
	"tn@Tunisia",
	"to@Tonga",
	"tr@Turkey",
	"tt@Trinidad and Tobago",
	"tv@Tuvalu",
	"tw@Taiwan",
	"tz@Tanzania",
	"ua@Ukraine",
	"ug@Uganda",
	"um@United States Minor Outlying Islands",
	"unknown@Unknown",
	"us@United States",
	"uy@Uruguay",
	"uz@Uzbekistan",
	"va@Vatican City",
	"vc@Saint Vincent and the Grenadines",
	"ve@Venezuela",
	"vg@Virgin Islands, British",
	"vi@Virgin Islands, U.S.",
	"vn@Vietnam",
	"vu@Vanuatu",
	"wa@Wales",
	"wf@Wallis and Futuna",
	"ws@Samoa",
	"ye@Yemen",
	"yt@Mayotte",
	"za@South Africa",
	"zm@Zambia",
	"zw@Zimbabwe"
);

?>
