<?php

$galaxyspecial = "Seed income is 50% OFF!";
$statustext = "(placeholder)";

$urgentmessage = "";

$contactemail = '(email)';

$apps = array(
	'Daisy' => array(
		'name' => 'Origami Daisy',
		'description' => "(Game calls itself \"Origami Daisy\", but you can choose whatever flower you'd like within the game)",
		'image' => 'img/app/icon_daisy.png',
		'folder' => 'daisy',
		'version_code' => 600,
		'version_nice' => '6.00',
		'download_file' => 'daisy.apk',
		'minver' => '2.2+',
		'size' => 1760222,
		'haschangelog' => true
	),
	'ABP' => array(
		'name' => 'Attack Breaker Pro',
		'description' => "This is a custom version that has various third-party junk ripped out.",
		'image' => 'img/ABPIcon.png',
		'folder' => 'abp',
		'version_code' => 600,
		'version_nice' => '6.00',
		'download_file' => 'abp.apk',
		'minver' => '1.6+',
		'size' => 173581,
		'haschangelog' => false
	)
);

//$flowers = array('Rose','Daisy','Iris','Orchid','Sunflower','Tulip');
$flowers = array('Rose','Daisy','Iris','Orchid','Sunflower');
$flowers_plural = array('Roses','Daisies','Irises','Orchids','Sunflowers');
$flowers_id = array('Rose' => 0,'Daisy' => 1,'Iris' => 2,'Orchid' => 3,'Sunflower' => 4);

$autowater_cost = 100;
$fertilizer_cost = 200;
$superfertilizer_cost = 20;

$debug = false;

$funfacts = array(
	"The warp music was made by Evershine.",
	"The original server was written in Java.",
	"Origami Rose existed for J2ME.",
	"There was a flower called Origami Buttercup that was only avalible on iOS.",
	"This server was written in PHP."
);

$countries = array(
	array("ad","Andorra"),
	array("ae","United Arab Emirates"),
	array("af","Afghanistan"),
	array("ag","Antigua and Barbuda"),
	array("ai","Anguilla"),
	array("al","Albania"),
	array("am","Armenia"),
	array("an","Netherlands Antilles"),
	array("ao","Angola"),
	array("ar","Argentina"),
	array("as","American Samoa"),
	array("at","Austria"),
	array("au","Austrailia"),
	array("aw","Aruba"),
	array("ax","Aland"),
	array("az","Azerbaijan"),
	array("ba","Bosnia and Herzegovina"),
	array("bb","Barbados"),
	array("bd","Bangladesh"),
	array("be","Belgium"),
	array("bf","Burkina Faso"),
	array("bg","Bulgaria"),
	array("bh","Bahrain"),
	array("bi","Burundi"),
	array("bj","Benin"),
	array("bm","Bermuda"),
	array("bn","Brunei Darussalam"),
	array("bo","Bolivia"),
	array("br","Brazil"),
	array("bs","Bahamas"),
	array("bt","Bhutan"),
	array("bw","Botswana"),
	array("by","Belarus"),
	array("bz","Belize"),
	array("ca","Canada"),
	array("cc","Cocos Islands"),
	array("cd","Congo, Democratic Republic of the"),
	array("cf","Central African Republic"),
	array("cg","Congo"),
	array("ch","Switzerland"),
	array("ci","Cote d'Ivoire"),
	array("ck","Cook Islands"),
	array("cl","Chile"),
	array("cm","Cameroon"),
	array("cn","China"),
	array("co","Colombia"),
	array("cr","Costa Rica"),
	array("cu","Cuba"),
	array("cv","Cape Verde"),
	array("cx","Christmas Island"),
	array("cy","Cyprus"),
	array("cz","Czech Republic"),
	array("de","Germany"),
	array("dj","Djibouti"),
	array("dk","Denmark"),
	array("dm","Dominica"),
	array("do","Dominican Republic"),
	array("dz","Algeria"),
	array("ec","Ecuador"),
	array("ee","Estonia"),
	array("eg","Egypt"),
	array("eh","Western Sahara"),
	array("en","England"),
	array("er","Eritrea"),
	array("es","Spain"),
	array("et","Ethiopia"),
	array("fam","Famfamfam Flag"),
	array("fi","Finland"),
	array("fj","Fiji"),
	array("fk","Falkland Islands"),
	array("fm","Micronesia"),
	array("fo","Faroe Islands"),
	array("fr","France"),
	array("ga","Gabon"),
	array("gb","United Kingdom"),
	array("gd","Grenada"),
	array("ge","Georgia"),
	array("gh","Ghana"),
	array("gi","Gibraltar"),
	array("gl","Greenland"),
	array("gm","Gambia"),
	array("gn","Guinea"),
	array("gp","Guadeloupe"),
	array("gq","Equatorial Guinea"),
	array("gr","Greece"),
	array("gs","South Georgia and the South Sandwich Islands"),
	array("gt","Guatemala"),
	array("gu","Guam"),
	array("gw","Guinea-Bissau"),
	array("gy","Guyana"),
	array("hk","Hong Kong"),
	array("hn","Honduras"),
	array("hr","Croatia"),
	array("ht","Haiti"),
	array("hu","Hungary"),
	array("id","Indonesia"),
	array("ie","Irland"),
	array("il","Israel"),
	array("in","India"),
	array("io","British Indian Ocean Territory"),
	array("iq","Iraq"),
	array("ir","Iran"),
	array("is","Iceland"),
	array("it","Italy"),
	array("jm","Jamaica"),
	array("jo","Jordan"),
	array("jp","Japan"),
	array("ke","Kenya"),
	array("kg","Kyrgyzstan"),
	array("kh","Cambodia"),
	array("ki","Kiribati"),
	array("km","Comoros"),
	array("kn","Saint Kitts and Nevis"),
	array("kp","North Korea"),
	array("kr","South Korea"),
	array("kw","Kuwait"),
	array("ky","Cayman Islands"),
	array("kz","Kazakhstan"),
	array("la","Laos"),
	array("lb","Lebanon"),
	array("lc","Saint Lucia"),
	array("li","Liechtenstein"),
	array("lk","Sri Lanka"),
	array("lr","Liberia"),
	array("ls","Lesotho"),
	array("lt","Lithuania"),
	array("lu","Luxembourg"),
	array("lv","Latvia"),
	array("ly","Libyan Arab Jamahiriya"),
	array("ma","Morocco"),
	array("mc","Monaco"),
	array("md","Moldova"),
	array("me","Montenegro"),
	array("mg","Madagascar"),
	array("mh","Marshall Island"),
	array("mk","Macedonia"),
	array("ml","Mali"),
	array("mm","Myanmar"),
	array("mn","Mongolia"),
	array("mo","Macao"),
	array("mp","Northern Mariana Islands"),
	array("mq","Martinique"),
	array("mr","Mauritania"),
	array("ms","Montserrat"),
	array("mt","Malta"),
	array("mu","Mauritius"),
	array("mv","Maldives"),
	array("mw","Malawi"),
	array("mx","Mexico"),
	array("my","Malaysia"),
	array("mz","Mozambique"),
	array("na","Nambia"),
	array("nc","New Caledonia"),
	array("ne","Niger"),
	array("nf","Norfolk Island"),
	array("ng","Nigeria"),
	array("ni","Nicaragua"),
	array("nl","Netherlands"),
	array("no","Norway"),
	array("np","Nepal"),
	array("nr","Nauru"),
	array("nu","Niue"),
	array("nz","New Zealand"),
	array("om","Oman"),
	array("pa","Panama"),
	array("pe","Peru"),
	array("pf","French Polynesia"),
	array("pg","Papua New Guinea"),
	array("ph","Philippines"),
	array("pk","Pakistan"),
	array("pl","Poland"),
	array("pm","Saint Pierre and Miquelon"),
	array("pn","Pitcairn"),
	array("pr","Puerto Rico"),
	array("ps","Palestinian Territory"),
	array("pt","Portugal"),
	array("pw","Palau"),
	array("py","Paraguay"),
	array("qa","Qatar"),
	array("ro","Romania"),
	array("rs","Serbia"),
	array("ru","Russia"),
	array("rw","Rwanda"),
	array("sa","Saudi Arabia"),
	array("sb","Solomon Islands"),
	array("sc","Seychelles"),
	array("scotland","Scotland"),
	array("sd","Sudan"),
	array("se","Sweden"),
	array("sg","Singapore"),
	array("sh","Saint Helena"),
	array("si","Slovenia"),
	array("sk","Slovakia"),
	array("sl","Sierra Leone"),
	array("sm","San Marino"),
	array("sn","Senegal"),
	array("so","Somalia"),
	array("sr","Suriname"),
	array("st","Sao Tome and Principe"),
	array("sv","El Salvador"),
	array("sy","Syrian Arab Republic"),
	array("sz","Swaziland"),
	array("tc","Turks and Caicos Islands"),
	array("td","Chad"),
	array("tf","French Southern Territories"),
	array("tg","Togo"),
	array("th","Thailand"),
	array("tj","Tajikistan"),
	array("tk","Tokelau"),
	array("tl","Timor-Leste"),
	array("tm","Turkmenistan"),
	array("tn","Tunisia"),
	array("to","Tonga"),
	array("tr","Turkey"),
	array("tt","Trinidad and Tobago"),
	array("tv","Tuvalu"),
	array("tw","Taiwan"),
	array("tz","Tanzania"),
	array("ua","Ukraine"),
	array("ug","Uganda"),
	array("um","United States Minor Outlying Islands"),
	array("unknown","Unknown"),
	array("us","United States"),
	array("uy","Uruguay"),
	array("uz","Uzbekistan"),
	array("va","Vatican City"),
	array("vc","Saint Vincent and the Grenadines"),
	array("ve","Venezuela"),
	array("vg","Virgin Islands, British"),
	array("vi","Virgin Islands, U.S."),
	array("vn","Vietnam"),
	array("vu","Vanuatu"),
	array("wa","Wales"),
	array("wf","Wallis and Futuna"),
	array("ws","Samoa"),
	array("ye","Yemen"),
	array("yt","Mayotte"),
	array("za","South Africa"),
	array("zm","Zambia"),
	array("zw","Zimbabwe")
);

?>
